name: tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Project
      run: |
        python -m pip install --upgrade pip setuptools wheel pytest
        python -m pip install pipenv
        pipenv install --deploy --system

    - name: Run Tests
      run: |
        pytest -v
